# Generated by Django 3.1.7 on 2021-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('nutrition_grade_fr', models.CharField(max_length=18)),
                ('traces', models.CharField(max_length=200)),
                ('allergens', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('id_openfoodfact', models.BigIntegerField()),
                ('image_front_url', models.CharField(max_length=200)),
                ('image_front_small_url', models.CharField(max_length=200)),
                ('ingredients_text', models.TextField()),
                ('fat_levels', models.CharField(max_length=20)),
                ('salt_levels', models.CharField(max_length=20)),
                ('saturated_fat_levels', models.CharField(max_length=20)),
                ('sugars_levels', models.CharField(max_length=20)),
                ('fat_100g', models.CharField(max_length=10)),
                ('salt_100g', models.CharField(max_length=10)),
                ('saturated_fat_100g', models.CharField(max_length=10)),
                ('sugars_100g', models.CharField(max_length=10)),
                ('category', models.ManyToManyField(to='food.Category')),
            ],
        ),
    ]
