# Generated by Django 3.1.7 on 2021-05-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stores', models.CharField(max_length=50)),
                ('nutrition_grade_fr', models.CharField(max_length=1)),
                ('traces', models.CharField(max_length=100)),
                ('allergens', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=50)),
                ('id_openfoodfact', models.BigIntegerField()),
                ('image_front_url', models.CharField(max_length=200)),
                ('image_front_small_url', models.CharField(max_length=200)),
                ('ingredients_text', models.TextField()),
                ('category', models.ManyToManyField(to='food.Category')),
            ],
        ),
    ]
