# Generated by Django 3.1.7 on 2021-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210506_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='nutrition_grade_fr',
            field=models.CharField(max_length=18),
        ),
    ]
