# Generated by Django 3.1.7 on 2021-05-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_substitut"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Substitut",
        ),
    ]
