# Generated by Django 3.1.7 on 2021-05-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20210506_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='allergens',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='stores',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='products',
            name='traces',
            field=models.CharField(max_length=200),
        ),
    ]
