# Generated by Django 3.1.7 on 2021-05-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0005_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="fat_levels",
        ),
        migrations.RemoveField(
            model_name="products",
            name="salt_levels",
        ),
        migrations.RemoveField(
            model_name="products",
            name="saturated_fat_levels",
        ),
        migrations.RemoveField(
            model_name="products",
            name="sugars_levels",
        ),
    ]
